[versions]
accompanist = "0.28.0"
accompanist-system-ui-controller = "0.30.1"
agp = "8.2.1"
android-version-name = "0.6.0"
android-version-code = "16"
android-target-sdk = "34"
android-compile-sdk = "34"
android-min-sdk = "26"
androidx-activity-compose = "1.9.0"
androidx-core = "1.13.1"
androidx-lifecycle = "2.7.0"
annotation = "1.7.1"
appcompat = "1.6.1"
compose = "1.6.2"
compose-ui = "1.5.1"
compose-plugin = "1.6.2"
coroutines-core = "1.8.0"
desktop-version-name = "1.0.0"
exposed = "0.46.0"
file-kit = "0.8.1"
foundation-desktop = "1.6.2"
gradle = "8.2.1"
gson = "2.10.1"
jaudiotagger = "3.0.1"
kmpalette = "2.2.0"
kotlin = "1.9.22"
kotlinx-serialization = "1.6.3"
koin = "3.5.3"
koin-compose = "1.1.2"
ktor = "2.3.10"
material-desktop = "1.6.2"
material3-desktop = "1.6.2"
media = "1.7.0"
multiplatform-settings = "1.1.1"
org-jetbrains-kotlin-jvm = "1.9.22"
room = "2.6.1"
sqlite-jdbc = "3.41.2.2"
vlcj = "4.8.3"
voyager = "1.1.0-alpha03"

[libraries]
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist-pager-indicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }
accompanist-system-ui-controller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist-system-ui-controller" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-appcompat-resources = { module = "androidx.appcompat:appcompat-resources", version.ref = "appcompat" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-media = { module = "androidx.media:media", version.ref = "media" }

components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose-plugin" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines-core" }
coroutines-core-jvm = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "coroutines-core" }
coroutines-core-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "coroutines-core" }

exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-crypt = { module = "org.jetbrains.exposed:exposed-crypt", version.ref = "exposed" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposed-java-time = { module = "org.jetbrains.exposed:exposed-java-time", version.ref = "exposed" }

foundation-desktop = { module = "org.jetbrains.compose.foundation:foundation-desktop", version.ref = "foundation-desktop" }
file-kit = { module = "io.github.vinceglb:filekit-compose", version.ref = "file-kit" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
jaudiotagger = { module = "net.jthink:jaudiotagger", version.ref = "jaudiotagger" }
kmpalette = { module = "com.kmpalette:kmpalette-core", version.ref = "kmpalette" }

koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin-compose" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }

ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negoctiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

material-desktop = { module = "org.jetbrains.compose.material:material-desktop", version.ref = "material-desktop" }
material3-desktop = { module = "org.jetbrains.compose.material3:material3-desktop", version.ref = "material3-desktop" }
multiplatform-settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatform-settings" }

vlcj = { module  = "uk.co.caprica:vlcj", version.ref = "vlcj"}

voyager-navigator = { module = "cafe.adriel.voyager:voyager-navigator", version.ref = "voyager" }
voyager-screen-model = { module = "cafe.adriel.voyager:voyager-screenmodel", version.ref = "voyager" }
voyager-transitions = { module = "cafe.adriel.voyager:voyager-transitions", version.ref = "voyager" }
voyager-koin = { module = "cafe.adriel.voyager:voyager-koin", version.ref = "voyager" }

room = { module = "androidx.room:room-ktx", version.ref = "room" }
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite-jdbc" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "org-jetbrains-kotlin-jvm" }

[bundles]
koin = ["koin-compose", "koin-core"]
accompanist = ["accompanist-pager","accompanist-system-ui-controller", "accompanist-pager-indicators"]
voyager = ["voyager-koin", "voyager-navigator", "voyager-screen-model", "voyager-transitions"]
exposed = ["exposed-core", "exposed-crypt", "exposed-dao", "exposed-java-time", "exposed-jdbc"]
androidx = ["androidx-activity-compose", "androidx-lifecycle", "androidx-core", "androidx-annotation", "androidx-appcompat", "androidx-appcompat-resources", "androidx-media"]
ktor = ["ktor-client-cio", "ktor-client-content-negoctiation", "ktor-client-core", "ktor-serialization-kotlinx-json"]